import {useEffect,useReducer,useRef,useState} from 'react';
import {ArrowUpRight,BookOpen,Check,CheckCheck,ChevronRight,Copy,Download,Keyboard,MessageCircle,Mic,Pause,Play,Plus,RotateCcw,Share2,ShieldCheck,Square,Trash2,Volume2,X} from 'lucide-react';
import {diffWordsWithSpace} from 'diff';
import {configuration,offlineConfig,request,type Config} from './api';
import {draftReducer,emptyDraft,externalResources,NOTEBOOK_KEY,randomId,readNotebook,writeNotebook,type Entry,type Mode} from './model';
import {startCapture,type Capture} from './recorder';

type RecordingState='idle'|'permission'|'recording'|'processing';
type LocalAudio={blob:Blob;url:string;filename:string};
const tabs:{id:Mode;label:string;icon:typeof Mic}[]=[{id:'speak',label:'Speak',icon:Mic},{id:'type',label:'Type',icon:Keyboard},{id:'notebook',label:'My notebook',icon:BookOpen},{id:'resources',label:'Ask ParkiBot',icon:MessageCircle}];
export default function App(){
  const [mode,setMode]=useState<Mode>('speak');
  const [draft,dispatch]=useReducer(draftReducer,emptyDraft);
  const [config,setConfig]=useState<Config>(offlineConfig);
  const [connected,setConnected]=useState(false);
  const [recording,setRecording]=useState<RecordingState>('idle');
  const [seconds,setSeconds]=useState(0),[level,setLevel]=useState(0);
  const [busy,setBusy]=useState(false),[speaking,setSpeaking]=useState(false),[paused,setPaused]=useState(false);
  const [notice,setNotice]=useState(''),[error,setError]=useState('');
  const [entries,setEntries]=useState<Entry[]>([]),[storageError,setStorageError]=useState('');
  const [localAudio,setLocalAudio]=useState<LocalAudio|null>(null);
  const [modal,setModal]=useState<'privacy'|'install'|'delete'|null>(null),[deleteId,setDeleteId]=useState<string|null>(null);
  const dialog=useRef<HTMLDialogElement>(null),heading=useRef<HTMLHeadingElement>(null);
  const capture=useRef<Capture|null>(null),captureAbort=useRef<AbortController|null>(null),requestAbort=useRef<AbortController|null>(null),localAudioUrl=useRef<string|null>(null);
  const operation=useRef(0),mounted=useRef(true),speechId=useRef(0);
  const deadline=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);

  function stopSpeech(){speechId.current++;window.speechSynthesis?.cancel();setSpeaking(false);setPaused(false);}
  function cancelRequests(){operation.current++;requestAbort.current?.abort();clearTimeout(deadline.current);setBusy(false);}
  function cancelCapture(){captureAbort.current?.abort();capture.current?.cancel();capture.current=null;setRecording('idle');setLevel(0);}
  function cancelAll(){cancelRequests();cancelCapture();stopSpeech();}
  useEffect(()=>{mounted.current=true;const c=new AbortController();const timeout=setTimeout(()=>c.abort(),5000);configuration(c.signal).then(value=>{setConfig(value);setConnected(true);}).catch(()=>{}).finally(()=>clearTimeout(timeout));try{setEntries(readNotebook());}catch{setStorageError('Your notebook could not be opened. Existing data has not been overwritten.');}
    const sync=(e:StorageEvent)=>{if(e.key===NOTEBOOK_KEY){try{setEntries(readNotebook());setStorageError('');}catch{setStorageError('Notebook changed in another tab and could not be read.');}}};window.addEventListener('storage',sync);
    return()=>{mounted.current=false;c.abort();requestAbort.current?.abort();captureAbort.current?.abort();capture.current?.cancel();clearTimeout(deadline.current);window.speechSynthesis?.cancel();if(localAudioUrl.current)URL.revokeObjectURL(localAudioUrl.current);window.removeEventListener('storage',sync);};},[]);
  useEffect(()=>{if(recording!=='recording')return;const started=performance.now();setSeconds(0);const timer=setInterval(()=>setSeconds(Math.floor((performance.now()-started)/1000)),250);return()=>clearInterval(timer);},[recording]);
  useEffect(()=>{const hidden=()=>{if(document.hidden&&(recording==='recording'||recording==='permission')){cancelCapture();setError('Recording stopped because the app was interrupted. Please start again when you are ready.');}};document.addEventListener('visibilitychange',hidden);return()=>document.removeEventListener('visibilitychange',hidden);},[recording]);
  useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close();},[modal]);
  function navigate(next:Mode){cancelAll();setMode(next);setNotice('');setError('');setTimeout(()=>heading.current?.focus(),0);}
  function beginRequest(){cancelRequests();const c=new AbortController();requestAbort.current=c;const id=operation.current;deadline.current=setTimeout(()=>c.abort(new DOMException('The service took too long.','TimeoutError')),40000);return {c,id};}
  function setLocalRecording(blob:Blob){if(localAudioUrl.current)URL.revokeObjectURL(localAudioUrl.current);const extension=blob.type.includes('mp4')?'mp4':blob.type.includes('ogg')?'ogg':'webm';const url=URL.createObjectURL(blob);localAudioUrl.current=url;setLocalAudio({blob,url,filename:`aeyron-recording-${new Date().toISOString().replace(/[:.]/g,'-')}.${extension}`});}
  function discardLocalRecording(){if(localAudioUrl.current)URL.revokeObjectURL(localAudioUrl.current);localAudioUrl.current=null;setLocalAudio(null);setNotice('Local recording discarded.');}
  function downloadLocalRecording(){if(!localAudio)return;const a=document.createElement('a');a.href=localAudio.url;a.download=localAudio.filename;a.click();setNotice('Recording download started.');}
  async function startRecording(){if(recording!=='idle')return;cancelAll();setError('');setNotice('');setRecording('permission');const c=new AbortController();captureAbort.current=c;
    try{const active=await startCapture(c.signal,blob=>{if(!c.signal.aborted&&mounted.current){capture.current=null;setLocalRecording(blob);setRecording('idle');setLevel(0);setNotice('Recording kept locally. It has not been uploaded.');}},message=>{if(!c.signal.aborted&&mounted.current){setError(message);setRecording('idle');}},setLevel);if(c.signal.aborted){active.cancel();return;}capture.current=active;setRecording('recording');}
    catch(e){if(!c.signal.aborted){setRecording('idle');setError(e instanceof DOMException&&e.name==='NotAllowedError'?'Microphone permission was denied. Allow it in your browser settings or use Type.':e instanceof Error?e.message:'Recording could not start.');}}
  }
  function edit(text:string){cancelRequests();stopSpeech();dispatch({type:'edit',text});setNotice('');}
  async function cleanup(){if(!draft.draft.trim()||busy)return;stopSpeech();const {c,id}=beginRequest(),revision=draft.revision;setBusy(true);setError('');
    try{const result=await request<{original:string;suggestion:string;warnings:string[];meaning_risk:string}>('rewrite',{text:draft.draft,style:'light_cleanup'},c.signal);if(id!==operation.current)return;if(typeof result.suggestion!=='string'||!Array.isArray(result.warnings))throw new Error('The suggestion could not be read. Your original is unchanged.');dispatch({type:'suggestion',revision,text:result.suggestion,warnings:result.warnings});}
    catch(e){if(id===operation.current)setError(c.signal.aborted?'Cleanup cancelled. Your message is unchanged.':e instanceof Error?e.message:'Cleanup is unavailable.');}
    finally{if(id===operation.current){clearTimeout(deadline.current);setBusy(false);}}
  }
  const approved=draft.approved!==null&&draft.approved===draft.draft;
  async function copy(){if(!approved)return;try{await navigator.clipboard.writeText(draft.approved!);setNotice('Message copied.');}catch{setError('Clipboard access was unavailable. Select and copy your approved message below.');}}
  async function share(){if(!approved)return;if(!navigator.share){await copy();return;}try{await navigator.share({text:draft.approved!});setNotice('Share window closed.');}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setError('Sharing was unavailable. You can copy the message instead.');}}
  function speak(){if(!approved)return;if(!window.speechSynthesis){setError('Read aloud is unavailable in this browser. Please copy your message.');return;}stopSpeech();const id=speechId.current;const utterance=new SpeechSynthesisUtterance(draft.approved!);utterance.rate=.9;utterance.onend=()=>{if(id===speechId.current)setSpeaking(false);};utterance.onerror=()=>{if(id===speechId.current){setSpeaking(false);setError('Playback stopped. Please try again.');}};window.speechSynthesis.speak(utterance);setSpeaking(true);}
  function save(){if(!approved)return;try{const current=readNotebook();const next=[{id:randomId(),text:draft.approved!,createdAt:new Date().toISOString()},...current];writeNotebook(next);setEntries(next);setStorageError('');setNotice('Saved on this device.');}catch(e){setError(e instanceof Error?e.message:'Unable to save. Please export or copy your message.');}}
  function remove(){try{if(deleteId===null){localStorage.removeItem(NOTEBOOK_KEY);setEntries([]);}else{const next=readNotebook().filter(e=>e.id!==deleteId);writeNotebook(next);setEntries(next);}setStorageError('');setModal(null);setNotice(deleteId===null?'Notebook cleared on this device.':'Entry deleted.');}catch{setError('Deletion failed. Your notebook has not been changed.');setModal(null);}}
  function downloadNotebook(){try{const current=readNotebook();const text=current.map(e=>new Date(e.createdAt).toLocaleString()+'\n'+e.text).join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='aeyron-notebook.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Export started. The downloaded file contains your private messages.');}catch{setError('The notebook could not be exported.');}}
  const showReview=!!draft.original||!!draft.draft;
  return <div className="app"><a className="skip-link" href="#workspace">Skip to workspace</a>
    <aside className="sidebar"><a href="#" className="brand" onClick={e=>{e.preventDefault();navigate('speak');}} aria-label="Aeyron Communicate home"><span className="brand-mark">a</span><span>Aeyron<span className="brand-sub">COMMUNICATE</span></span></a>
      <p className="nav-label">YOUR SPACE</p><nav aria-label="Main navigation">{tabs.map(t=><button key={t.id} className={'nav-item '+(mode===t.id?'active':'')} aria-current={mode===t.id?'page':undefined} onClick={()=>navigate(t.id)}><t.icon size={21}/><span>{t.label}</span>{mode===t.id&&<ChevronRight size={17} className="nav-arrow"/>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="control-note"><ShieldCheck size={25}/><strong>Your words. Your choice.</strong><p>Nothing is shared until you choose to share it.</p></div><button className="text-button" onClick={()=>setModal('privacy')}>Privacy & data</button><button className="text-button" onClick={()=>setModal('install')}>Install Aeyron <ArrowUpRight size={15}/></button><span className="preview-label">EARLY ACCESS · 0.1</span></div>
    </aside>
    <main id="workspace" className="main"><header className="topbar"><span>Communication, at your pace</span><span className="device-badge"><ShieldCheck size={15}/> No account needed</span></header>
      <div className="content"><div className="page-heading"><div><p className="eyebrow">{mode==='notebook'?'A LITTLE SPACE FOR YOUR WORDS':mode==='resources'?'INFORMATION & SUPPORT':'MAKE ROOM FOR YOUR VOICE'}</p><h1 ref={heading} tabIndex={-1}>{mode==='speak'?'Take your time. We’re listening.':mode==='type'?'Your thoughts, in your words.':mode==='notebook'?'My notebook':'Ask about Parkinson’s.'}</h1><p>{mode==='speak'?'Record at your own pace. Your audio stays in this browser.':mode==='type'?'Start with whatever you want to say. You approve every word.':mode==='notebook'?'Messages you chose to keep. Only on this device.':'An optional connection to an independent information service.'}</p></div>{showReview&&mode!=='notebook'&&mode!=='resources'&&<button className="button quiet" onClick={()=>{cancelAll();dispatch({type:'clear'});setNotice('Started a new message.');}}><Plus size={18}/> New message</button>}</div>
      <div role="status" aria-live="polite" className={notice?'notice':'sr-only'}>{notice}</div>{error&&<div role="alert" className="error">{error}<button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={18}/></button></div>}
      {(mode==='speak'||mode==='type')&&<div className="workspace-grid"><section className="composer card" aria-label="Message composer"><div className="card-heading"><span className="step">01</span><h2>{mode==='speak'?'Say what’s on your mind':'Write what’s on your mind'}</h2><span className="subtle-pill">{mode==='speak'?'Record locally':'Private until submitted'}</span></div>
        {mode==='speak'?<><div className={'recording-surface '+(recording==='recording'?'is-recording':'')}><div className="mic-orbit"><Mic size={34}/><div className="level-ring" style={{transform:`scale(${1+level*.25})`,opacity:recording==='recording'?.25+level*.5:0}}/></div><h3>{recording==='recording'?'Listening. Take your time.':recording==='processing'?'Turning your speech into text…':recording==='permission'?'Waiting for microphone permission…':'A little pause is perfectly okay.'}</h3><p>{recording==='recording'?`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')} / 01:30`:recording==='processing'?'Your original message will appear below for you to check.':'You choose when to start and stop. Up to 90 seconds.'}</p>
        {recording==='idle'?<button className="button primary record-button" onClick={()=>void startRecording()}><Mic size={20}/> Start recording</button>:recording==='recording'?<button className="button danger record-button" onClick={()=>capture.current?.stop()}><Square size={18}/> Stop recording</button>:null}
        {recording!=='idle'&&<button className="text-button" onClick={()=>{cancelAll();setNotice('Recording and processing cancelled.');}}>Cancel</button>}</div>
        <div className="service-note"><ShieldCheck size={21}/><div><strong>Local-only recording</strong><p>Your audio stays in this browser and is not sent to Aeyron or a speech provider.</p></div></div>
        {localAudio&&<section className="local-audio" aria-label="Local recording"><h3>Recording ready</h3><audio controls preload="metadata" src={localAudio.url} aria-label="Your local recording"/><p className="helper">This recording exists only in this tab until you download or discard it.</p><div className="output-buttons"><button className="button quiet" onClick={downloadLocalRecording}><Download size={18}/> Download recording</button><button className="button danger" onClick={discardLocalRecording}><Trash2 size={18}/> Discard recording</button></div></section>}</> 
        :<div className="type-surface"><label htmlFor="thoughts">What would you like to say?</label><textarea id="thoughts" placeholder="Start anywhere. A few words or a whole thought…" rows={7} maxLength={4000} value={draft.draft} onChange={e=>{cancelRequests();stopSpeech();dispatch({type:'input',text:e.target.value});setNotice('');}}/><div className="input-foot"><span>It doesn’t have to be perfectly written.</span><span>{draft.draft.length} / 4,000</span></div></div>}
        {showReview&&<div className="review"><div className="review-title"><span className="step">02</span><h2>Make it yours</h2></div><details className="original"><summary>View original {mode==='speak'?'transcript':'input'}</summary><p>{draft.original}</p></details><label htmlFor="message">Your message</label><textarea id="message" rows={4} maxLength={4000} value={draft.draft} onChange={e=>edit(e.target.value)}/><div className="edit-actions"><button className="button quiet" onClick={()=>void cleanup()} disabled={busy||!draft.draft.trim()||!connected}><RotateCcw size={17}/>{busy?'Cleaning up…':'Light cleanup'}</button><button className="text-button" onClick={()=>{cancelRequests();stopSpeech();dispatch({type:'undo'});}}>Undo changes</button></div><p className="helper">{connected?'Cleanup only adjusts spacing. It does not add or interpret your thoughts.':'Cleanup is offline. You can still edit and approve your message.'}</p>
        {draft.suggestion!==null&&<section className="suggestion" aria-label="Suggested changes"><h3>Suggested changes</h3><p className="diff">{diffWordsWithSpace(draft.draft,draft.suggestion).map((part,i)=>part.added?<ins key={i}>{part.value}</ins>:part.removed?<del key={i}>{part.value}</del>:<span key={i}>{part.value}</span>)}</p>{draft.warnings.map((w,i)=><p className="helper" key={i}>{w}</p>)}<button className="button quiet" onClick={()=>{stopSpeech();dispatch({type:'useSuggestion'});}}>Use this version</button></section>}
        <button className={'button approve '+(approved?'approved':'primary')} disabled={!draft.draft.trim()||busy||recording!=='idle'} onClick={()=>{cancelRequests();dispatch({type:'approve'});setNotice('Message approved. Choose an action below.');}}>{approved?<CheckCheck size={20}/>:<Check size={20}/>} {approved?'Approved by you':'This is what I want to say'}</button>
        {approved&&<section className="output" aria-label="Approved message actions"><p className="output-text">{draft.approved}</p><div className="output-buttons"><button className="button quiet" onClick={()=>void copy()}><Copy size={18}/> Copy</button><button className="button quiet" onClick={()=>void share()}><Share2 size={18}/> Share</button><button className="button quiet" onClick={speak}><Volume2 size={18}/> Read aloud</button><button className="button quiet" onClick={save}><BookOpen size={18}/> Save privately</button></div>{speaking&&<div className="output-buttons"><button className="button quiet" onClick={()=>{if(paused)window.speechSynthesis.resume();else window.speechSynthesis.pause();setPaused(!paused);}}>{paused?<Play size={18}/>:<Pause size={18}/>} {paused?'Resume':'Pause'}</button><button className="button danger" onClick={stopSpeech}><Square size={18}/> Stop playback</button></div>}</section>}
        </div>}
      </section><aside className="context-column"><section className="card guide"><span className="small-icon"><MessageCircle size={23}/></span><h2>One thought at a time.</h2><p>There’s no rush. Aeyron is here to help you communicate, not to judge how you sound.</p><ol><li><span>1</span><div><strong>Speak or type</strong><p>Use your own words and pace.</p></div></li><li><span>2</span><div><strong>Check your message</strong><p>Edit anything that isn’t right.</p></div></li><li><span>3</span><div><strong>Choose what happens next</strong><p>Copy, share, speak, or keep it.</p></div></li></ol></section><section className="privacy-card"><ShieldCheck size={22}/><div><h3>You stay in control.</h3><p>No background recording. No automatic sharing. Your notebook stays on this device.</p><button className="text-button" onClick={()=>setModal('privacy')}>How your data is handled <ArrowUpRight size={15}/></button></div></section></aside></div>}
      {mode==='notebook'&&<section className="card notebook"><div className="notebook-toolbar"><h2>{entries.length} saved {entries.length===1?'message':'messages'}</h2><div className="output-buttons"><button className="button quiet" disabled={!entries.length} onClick={downloadNotebook}><Download size={18}/> Export</button><button className="button quiet" disabled={!entries.length&&!storageError} onClick={()=>{setDeleteId(null);setModal('delete');}}><Trash2 size={18}/> Clear all</button></div></div><p className="helper">Only save on a device you trust. Browser cleanup can erase these entries. Exports contain readable private text.</p>{storageError&&<p role="alert" className="error">{storageError}</p>}{!entries.length?<div className="empty-state"><BookOpen size={40}/><h3>A place for words worth keeping.</h3><p>Save an approved message and it will appear here.</p><button className="button primary" onClick={()=>navigate('type')}><Plus size={18}/> Write a message</button></div>:<div className="entry-grid">{entries.map(e=><article className="entry" key={e.id}><time dateTime={e.createdAt}>{new Date(e.createdAt).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})}</time><p>{e.text}</p><div className="entry-actions"><button className="text-button" onClick={()=>{cancelAll();dispatch({type:'input',text:e.text});setMode('type');setNotice('Saved message opened. Review and approve it before using.');}}>Open message <ArrowUpRight size={15}/></button><button className="icon-button" aria-label="Delete saved message" onClick={()=>{setDeleteId(e.id);setModal('delete');}}><Trash2 size={19}/></button></div></article>)}</div>}</section>}
      {mode==='resources'&&<section className="card resources"><span className="small-icon"><MessageCircle size={27}/></span><p className="eyebrow">INDEPENDENT EXTERNAL RESOURCE</p><h2>Meet ParkiBot.</h2><p>A chatbot for questions about Parkinson’s. It opens separately from Aeyron.</p><div className="resource-notice"><ShieldCheck size={23}/><p>ParkiBot is an independent Parkinson’s information service. Aeyron does not send your message or notebook data to ParkiBot. Review important health information with a qualified professional.</p></div><a className="button primary" href={externalResources.parkibot} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">Open ParkiBot <ArrowUpRight size={19}/></a><p className="helper">A third-party website with its own privacy terms. No affiliation or endorsement is implied.</p></section>}
      <footer className="footer"><span>Aeyron helps you express what you intended. You approve every word.</span><span>Communication assistance · Not medical advice</span></footer>
      </div>
    </main>
    <dialog ref={dialog} onCancel={()=>setModal(null)} onClose={()=>setModal(null)} aria-labelledby="dialog-title"><div className="dialog-top"><h2 id="dialog-title">{modal==='delete'?'Delete saved messages?':modal==='install'?'Keep Aeyron close':'Your data, explained'}</h2><button className="icon-button" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={22}/></button></div>{modal==='privacy'?<div className="dialog-copy"><p><strong>Typing:</strong> Editing, approval, and local notebook actions happen in this browser. Selecting Light cleanup sends that message to Aeyron’s backend for spacing-only cleanup.</p><p><strong>Speech:</strong> {config.retention_notice}</p><p>When configured, recordings are processed temporarily. Aeyron’s temporary-copy deletion does not establish deletion by an external provider. Check the deployment’s provider policy before recording sensitive information.</p><p><strong>Notebook:</strong> Stored only in this browser, unencrypted by this app. Other people using your device may see it. Browser cleanup can erase it.</p><p><strong>Read aloud:</strong> Uses your browser’s speech service. Depending on the installed voice and device, processing may use an external service. Do not assume it is offline.</p><p><strong>ParkiBot:</strong> Opens a separate website. No messages are sent in the handoff.</p><p>No research collection, background recording, analytics, or model-training reuse is enabled by Aeyron.</p></div>:modal==='install'?<div className="dialog-copy"><p><strong>iPhone or iPad:</strong> In Safari, open Share and choose Add to Home Screen.</p><p><strong>Android:</strong> Open the browser menu and choose Install app or Add to Home screen, if available.</p><p><strong>Computer:</strong> Look for Install in your browser’s address bar or menu.</p><p>You can always use the website without installing it. After one online visit, typing and your notebook can work offline. Speech needs the configured service.</p></div>:<><p>{deleteId===null?'This removes all saved notebook entries from this browser. Download an export first if you want to keep them.':'This removes the selected message from this browser.'} This cannot be undone here.</p><div className="output-buttons"><button className="button quiet" onClick={()=>setModal(null)}>Keep messages</button><button className="button danger" onClick={remove}>Delete {deleteId===null?'all':'message'}</button></div></>}</dialog>
  </div>;
}
